apiVersion: apps/v1
kind: Deployment
metadata:
  name: elemana-frontend
  labels:
    app: elemana-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elemana-frontend
  template:
    metadata:
      labels:
        app: elemana-frontend
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: elemana-frontend
        image: ghcr.io/mohamedsalem66/elemana-frontend:0.1-SNAPSHOT
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 30

---

apiVersion: v1
kind: Service
metadata:
  name: elemana-frontend
  labels:
    app: elemana-frontend
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: elemana-frontend
